### ISSUE TITLE
Errors converting SIARD back to database with external LOBs

### ISSUE THREAD

**Issue by DavidUnderdown** [keeps/dbptk-developer#421]
Description: 
This may be a duplicate of #399. Having created a SIARD package with externalised LOBs I wan't to convert the SIARD package back to a database. 

When the inserts are being done for tables with LOBs see error messages reported eg <Line 9, Column 172>: XML-24523: (Error) Invalid value '..\2019-15-10-DMO_DWH.siard_lobseg_1\content\schema10\table80\lob6\record1.txt' for attribute: 'file'

Steps required to reproduce the bug:

1. Created SIARD 2.1 package from MSSQL database with option --export-external-lobs set
2. Recreate database in MSSQL from SIARD 2.1 package
3. Errors reported related to the externalised LOB files

Attach the dbptk-app.log.txt file below.
Extract given, can add full file if required later:

> 2019-11-28 16:59:32,152 [main] ERROR (c.d.m.s.i.c.SAXErrorHandler) line: 9; column: 172; <Line 9, Column 172>: XML-24523: (Error) Invalid value '..\2019-15-10-DMO_DWH.siard_lobseg_1\content\schema10\table80\lob6\record1.txt' for attribute: 'file'
org.xml.sax.SAXParseException: <Line 9, Column 172>: XML-24523: (Error) Invalid value '..\2019-15-10-DMO_DWH.siard_lobseg_1\content\schema10\table80\lob6\record1.txt' for attribute: 'file'
	at oracle.xml.parser.v2.XMLError.flushErrorHandler(XMLError.java:425)
	at oracle.xml.parser.v2.XMLError.flushErrors1(XMLError.java:290)
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:415)
	at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:236)
	at com.databasepreservation.modules.siard.in.content.SIARD2ContentImportStrategy.importContent(SIARD2ContentImportStrategy.java:184)
	at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.migrateDatabaseTo(SIARDImportDefault.java:60)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:102)
	at com.databasepreservation.Main.runMigration(Main.java:295)
	at com.databasepreservation.Main.internalMain(Main.java:122)
	at com.databasepreservation.Main.main(Main.java:76)
2019-11-28 16:59:32,163 [main] ERROR (c.d.m.s.i.c.SIARD2ContentImportStrategy) An error occurred converting table contents
com.databasepreservation.model.exception.ModuleException: Parsing or validation error occurred while reading XML table file (details are above)
	at com.databasepreservation.modules.siard.in.content.SIARD2ContentImportStrategy.importContent(SIARD2ContentImportStrategy.java:194)
	at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.migrateDatabaseTo(SIARDImportDefault.java:60)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:102)
	at com.databasepreservation.Main.runMigration(Main.java:295)
	at com.databasepreservation.Main.internalMain(Main.java:122)
	at com.databasepreservation.Main.main(Main.java:76)

>

**Comment by DavidUnderdown** [comment]
Is that I need to use a filter in this case? I can't quite make out the documentation on that.
