### ISSUE TITLE
JDBC driver does not work with SQLite database

### ISSUE THREAD

**Issue by cjwomack** [keeps/dbptk-developer#511]
Description: The JDBC driver does not work with SQLite database due to the fact a SQLite file has only 1 database in each file ever and it is referred to as main when connected (As far as I can tell) [See sqlite-jdbc](https://stackoverflow.com/questions/7313190/how-to-name-an-sqlite-database-so-it-doesnt-have-the-default-name-of-main)

This can be seen in the JDBC driver in the getCatalog() function (https://github.com/xerial/sqlite-jdbc/blob/ada2b147dc858ef557a995e2f4ef25f7c65fc6a7/src/main/java/org/sqlite/jdbc3/JDBC3Connection.java#L27)

The relevant line in the code referring to getCatalog() is [getDatabaseName() function](https://github.com/keeps/dbptk-developer/blob/b2a438c65cd1a12c43345089f8ab84e6d35b4d07/dbptk-modules/dbptk-module-jdbc/src/main/java/com/databasepreservation/modules/jdbc/in/JDBCImportModule.java#L438)

Steps required to reproduce the bug:

1.  Get a SQLite DB (such as [Chinook DB](https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip) from [www.sqlitetutorial.net](https://www.sqlitetutorial.net/sqlite-sample-database/)) and [JDBC driver for SQLite](https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.36.0.3/sqlite-jdbc-3.36.0.3.jar)
2.  For Windows use:
`java "-Dfile.encoding=UTF-8" -cp "C:\path\to\dbptk-app-x.y.z.jar;C:\path\to\sqlite-jdbc-3.36.0.3.jar" com.databasepreservation.Main migrate --import=jdbc --import-driver=org.sqlite.JDBC     --import-connection="jdbc:sqlite:C:\path\to\database"   -e siard-2 -ef C:\path\to\output.siard`

Adjust for other operating systems accordingly.

So it looks like the JDBC driver needs to be modified or a specific SQLite driver based off the JDBC driver.

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/8761796/dbptk-app.log.txt)

**Comment by luis100** [comment]
Could you try this?
`--import-connection=jdbc:sqlite:C:/Users/Clarissa/Downloads/chinook/chinook.db`

**Comment by cjwomack** [comment]
I didn't not want to plaster my filepaths on the internet. Of course I changed it to my specifics

**Comment by luis100** [comment]
Sure, but it seems you have add a ":thin:" that is not needed.
Your connection string is "jdbc:sqlite:thin:<path>" but it should be "jdbc:sqlite:<path>".

**Comment by cjwomack** [comment]
My computer crashed last night.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

PS C:\Users\Clarissa> java -cp "C:\Users\Clarissa\Downloads\dbptk-app-2.10.0.jar;C:\Users\Clarissa\Downloads\sqlite-jdbc-3.36.0.3.jar" com.databasepreservation.Main migrate --import=jdbc --import-driver=org.sqlite.JDBC     --import-connection="jdbc:sqlite:thin:C:\Users\Clarissa\Downloads\chinook\chinook.db"   -e siard-2 -ef C:\Users\Clarissa\Downloads\output2.siard
ERROR The charset in use is not UTF-8.
      Please try forcing UTF-8 charset by running the application with:
         java "-Dfile.encoding=UTF-8" -jar ...
      Log files and migration reports were saved in C:\Users\Clarissa\Downloads
      Troubleshooting information can be found at https://github.com/keeps/dbptk-developer/wiki/Troubleshooting
      Please report any problems at https://github.com/keeps/dbptk-developer/issues/new
PS C:\Users\Clarissa> java "-Dfile.encoding=UTF-8" -cp "C:\Users\Clarissa\Downloads\dbptk-app-2.10.0.jar;C:\Users\Clarissa\Downloads\sqlite-jdbc-3.36.0.3.jar" com.databasepreservation.Main migrate --import=jdbc --import-driver=org.sqlite.JDBC     --import-connection="jdbc:sqlite:thin:C:\Users\Clarissa\Downloads\chinook\chinook.db"   -e siard-2 -ef C:\Users\Clarissa\Downloads\output2.siard
      Converting database: jdbc to siard-2
      Initializing database
      Exporting SIARD version 2.1
ERROR Fatal error while converting the database (path to 'thin:C:\Users\Clarissa\Downloads\chinook\chinook.db': 'C:\Users\Clarissa\thin:C:' does not exist)
      Log files and migration reports were saved in C:\Users\Clarissa\Downloads
      Troubleshooting information can be found at https://github.com/keeps/dbptk-developer/wiki/Troubleshooting
      Please report any problems at https://github.com/keeps/dbptk-developer/issues/new
PS C:\Users\Clarissa> java "-Dfile.encoding=UTF-8" -cp "C:\Users\Clarissa\Downloads\dbptk-app-2.10.0.jar;C:\Users\Clarissa\Downloads\sqlite-jdbc-3.36.0.3.jar" com.databasepreservation.Main migrate --import=jdbc --import-driver=org.sqlite.JDBC     --import-connection="jdbc:sqlite:C:\Users\Clarissa\Downloads\chinook\chinook.db"   -e siard-2 -ef C:\Users\Clarissa\Downloads\output2.siard
      Converting database: jdbc to siard-2
      Initializing database
      Exporting SIARD version 2.1
      Obtained database structure
      Exporting database structure
ERROR Fatal error while converting the database (Error while exporting structure: dbname cannot be blank)
      A report was generated with a listing of information that was modified during the conversion.
      The report file is located at C:\Users\Clarissa\Downloads\dbptk-report-20220524201458245.txt
      Log files and migration reports were saved in C:\Users\Clarissa\Downloads
      Troubleshooting information can be found at https://github.com/keeps/dbptk-developer/wiki/Troubleshooting
      Please report any problems at https://github.com/keeps/dbptk-developer/issues/new
PS C:\Users\Clarissa>

**Comment by cjwomack** [comment]
That was before I posted this issue

**Comment by cjwomack** [comment]
I'll run it again in a nice new file

**Comment by luis100** [comment]
Hum, yes, I see that the SQLite JDBC client provides and empty database name, which is not permitted in SIARD.

```
2022-05-24 21:00:47,256 [main] ERROR (c.d.Main) Fatal error while converting the database (Error while exporting structure: dbname cannot be blank)
com.databasepreservation.model.exception.ModuleException: Error while exporting structure: dbname cannot be blank
	at com.databasepreservation.modules.siard.out.metadata.SIARD21MetadataExportStrategy.jaxbSiardArchive(SIARD21MetadataExportStrategy.java:266)
	at com.databasepreservation.modules.siard.out.metadata.SIARD21MetadataExportStrategy.writeMetadataXML(SIARD21MetadataExportStrategy.java:186)
	at com.databasepreservation.modules.siard.out.output.SIARDExportDefault.finishDatabase(SIARDExportDefault.java:175)
	at com.databasepreservation.model.modules.filters.IdentityFilter.finishDatabase(IdentityFilter.java:103)
	at com.databasepreservation.model.modules.filters.ObservableFilter.finishDatabase(ObservableFilter.java:151)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.migrateDatabaseTo(JDBCImportModule.java:2143)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:123)
	at com.databasepreservation.Main.runMigration(Main.java:294)
	at com.databasepreservation.Main.internalMain(Main.java:125)
	at com.databasepreservation.Main.main(Main.java:81)
```
I guess that for this specific case, we actually need and specialized implementation of a SQLlite import module so it gets the database name from the file name it loads.

**Comment by cjwomack** [comment]
So maybe need to create an arbitrary name for the sqlite jdbc driver?

**Comment by luis100** [comment]
I don't see any work-around this issue without development. Or the generic JDBC module creates a default database name or allows a parameter to override the database name, or a new module is created just for SQLLite to fix this situation. Anyway, code needs to be developed.

**Comment by cjwomack** [comment]
I agree. So the class name of the sqlite driver is org.sqlite.JDBC and I assume that is in this.driverClassName??
So could an if statement be used in getDatabaseName()??? 

  protected String getDatabaseName() throws SQLException, ModuleException {
 
    return getConnection().getCatalog();
  }

**Comment by luis100** [comment]
I am not an expert in SQLLite, but it seems it does not have the concept of database name and therefore the JDBC client does not provide one. In my view, this information should be replaced by the file name of the SQLLite database, in your example "chinook". But this is a very specific situation for SQLLite, and therefore it should be part of a specialized module for this database, which could also make it easier to load the database from a selected file and skip the requirement of loading the driver jar.

**Comment by MartinR4838** [comment]
Hello, 
problem seems not solved in v. 2.10.3 but with sqlite-jdbc-3.39.3.0.jar dbptk-app now reports "ERROR Fatal error while converting the database (Error while Marshalling JAXB)" and not the one with blank name. SIAD file is produced but only with /header folder is inside and metadata.xml file is empty.
[dbptk_2_10_3_jdbc_sqlite.zip](https://github.com/keeps/dbptk-developer/files/10123452/dbptk_2_10_3_jdbc_sqlite.zip)
