### ISSUE TITLE
SQL 2022 to SIARD2 - The conversion from varbinary to BLOB is unsupported

### ISSUE THREAD

**Issue by pi-r-ayotte** [keeps/dbptk-developer#607]
Description: Unable to export table containing varbinary column on SQL Server 2022

Steps required to reproduce the bug:

1. Create a Test database
2. Run the tcl script (see below) to create a test table
3. Try to export (cmdline used: java -jar "-Dfile.encoding=UTF-8" dbptk-app-2.11.0.jar migrate --import microsoft-sql-server --import-server-name=sql2022 --import-database="Test" --import-username=userna --import-password="pwd" --export siard-2 --export-file=G:\export\Test-dbptk.siard)
4. You should find the error in the dbptk-app.log

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/15355633/dbptk-app.log.txt)

TCL Script

USE [Test]
GO
/****** Object:  Table [dbo].[AlarmEnroll]    Script Date: 5/17/2024 2:18:51 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AlarmEnroll1](
	[ObjPropRef] [varbinary](128) NULL,
) 
GO
USE [Test]
GO
INSERT INTO [dbo].[AlarmEnroll1]
           ([ObjPropRef])
     VALUES
           (0)
GO

**Comment by stighemmer** [comment]
I am also affected.
Also using SQL server 2022
I tested both 2.11.0 and 3.0.4 and got the same error.

**Comment by luis100** [comment]
Underlying error:
```log
com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from varbinary to BLOB is unsupported.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237)
	at com.microsoft.sqlserver.jdbc.DataTypes.throwConversionError(DataTypes.java:1112)
	at com.microsoft.sqlserver.jdbc.ServerDTVImpl.getValue(dtv.java:3704)
	at com.microsoft.sqlserver.jdbc.DTV.getValue(dtv.java:247)
	at com.microsoft.sqlserver.jdbc.Column.getValue(Column.java:190)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2077)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2063)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getBlob(SQLServerResultSet.java:2829)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.rawToCellSimpleTypeBinary(JDBCImportModule.java:1923)
```

This is a MS SQLServer JDBC driver error, maybe due to a wrong configuration on the SQL Server side.
- https://stackoverflow.com/a/47407467

Not sure if there a work-around that would not require changes in the SQL Server schema.
