### ISSUE TITLE
SIARD CLI validate: Exception in thread "main" java.lang.IllegalAccessError: class 

### ISSUE THREAD

**Issue by Chlara** [keeps/dbptk-developer#626]
Hi

If I want to validate a siard file with the commandline, I receive the follwing Exception:

> java -jar dbptk-app-3.0.1.jar validate -if SIARD-2.1_Northwind.siard
      Validate SIARD at 'SIARD-2.1_Northwind.siard'
Exception in thread "main" java.lang.IllegalAccessError: class com.databasepreservation.modules.siard.validate.component.tableData.RequirementsForTableDataValidator (in unnamed module @0x77ec78b9) cannot access class com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.jaxp to unnamed module @0x77ec78b9
        at com.databasepreservation.modules.siard.validate.component.tableData.RequirementsForTableDataValidator.<init>(RequirementsForTableDataValidator.java:145)
        at com.databasepreservation.modules.siard.validate.component.factories.RequirementsForTableDataComponentFactory.buildComponent(RequirementsForTableDataComponentFactory.java:55)
        at com.databasepreservation.modules.siard.validate.SIARDValidateModule.getValidationComponents(SIARDValidateModule.java:208)
        at com.databasepreservation.modules.siard.validate.SIARDValidateModule.validate(SIARDValidateModule.java:121)
        at com.databasepreservation.SIARDValidation.validate(SIARDValidation.java:92)
        at com.databasepreservation.Main.runValidation(Main.java:191)
        at com.databasepreservation.Main.internalMain(Main.java:129)
        at com.databasepreservation.Main.main(Main.java:81)

See also: [dbptk-app.log.txt](https://github.com/user-attachments/files/17504185/dbptk-app.log.txt)
The reports are created but empty.

The same SIARD file can be validate with the Desktop Version from DBPTK. And the command "java -jar dbptk-app-3.0.1.jar edit -if SIARD-2.1_valid_Northwind_3_2b.siard -l" works fine.

[dbptk-validation-reporter-SIARD-2.1_Northwind-20241024104353744.txt](https://github.com/user-attachments/files/17504198/dbptk-validation-reporter-SIARD-2.1_Northwind-20241024104353744.txt)
[dbptk-app.log.txt](https://github.com/user-attachments/files/17504199/dbptk-app.log.txt)
[dbptk-report-20241024104353744.txt](https://github.com/user-attachments/files/17504200/dbptk-report-20241024104353744.txt)

**Comment by Chlara** [comment]
The problem continues to occur. 
This happens on different computers and with different Java 21 manufacturers (Bellsoft and Adoptium).

**Comment by hmiguim** [comment]
Fixed in version 3.0.2
